# Setup
title: y1lan's blogs
# tagline:             ''
description: "A student without brains."
url: https://y1lan.github.io
baseurl: ""
paginate: 5
# permalink:           pretty

# About/contact
author:
  avatar: /public/y1lan_icon.jpg
  name: y1lan
  email: y1lan@outlook.com
  github: y1lan


# Gems
plugins:
  - jekyll-paginate

# syntax highlight
highlighter: rouge
# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
